### PR TITLE
ci: do not force python3.7

### PR DESCRIPTION
**Pull request by proppy**
This is a lame attempt at fixing #324.

/cc @xobs @PiotrZierhoffer @ajelinski

### CODE REVIEW

**Comment by mithro** [comment]
@proppy - We should probably be building against all Conda supported Python versions - https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-python.html

> Conda supports Python 3.8, 3.9, 3.10, and 3.11.

**Comment by proppy** [comment]
> @proppy - We should probably be building against all Conda supported Python versions - 

I think that's orthogonal to the version of python installed on the host; a given package should be able to specify the version of conda to build against in the workflow, see: https://github.com/hdl/conda-eda/blob/master/.github/workflows/Build.yml#L117

**Comment by proppy** [comment]
>  building against all Conda supported Python versions 

Updated #190 to be more generic to track this.

**Comment by mithro** [comment]
Nothing should depend on the host's Python, it should be using the Python from conda?

**Comment by proppy** [comment]
> Nothing should depend on the host's Python, it should be using the Python from conda?

Yes, that's my understanding as well that the conda's python is used after entering the recipe build procress, but I assume it is also installed on the host as some of the bootstrap scripts might require it?

**Comment by xobs** [comment]
I don't think it uses Python from the system, even when doing setup.

A similar-but-orthogonal issue is that a particular Python might not be available on the system. For example, `python3.7` is unavailable on arm64, which is why openroad doesn't build on that platform.

**Pull request merged**
