### PR TITLE
pnr/openroad disable mpl2

### LINKED ISSUE #258: openroad package fails to build
https://github.com/hdl/conda-eda/actions/runs/3492792934/jobs/5846941441

```
  CMake Error at src/mpl2/CMakeLists.txt:42 (find_package):
    By not providing "Findortools.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "ortools", but
    CMake did not find one.
  
    Could not find a package configuration file provided by "ortools" with any
    of the following names:
  
      ortoolsConfig.cmake
      ortools-config.cmake
  
    Add the installation prefix of "ortools" to CMAKE_PREFIX_PATH or set
    "ortools_DIR" to a directory containing one of the above files.  If
    "ortools" provides a separate development package or SDK, be sure it has
    been installed.
  ```
seems like a new? dependency is missing.

### PR DESCRIPTION
**Pull request by proppy**
- disable mpl2 until we get or-tools packaged

Fixes #258

### CODE REVIEW

**Comment by proppy** [comment]
@maliberty @donn is mpl2 currently used in OpenLane?

**Comment by donn** [comment]
@proppy Not that I know of

**Comment by maliberty** [comment]
openlane mostly uses manual macro placement today afaik

**Comment by saicharan0112** [comment]
Not sure who is responsible for this, but can this be merged please? Not having the openroad latest conda package is delaying OpenFASOC's tests with the latest version of openroad. 

@PiotrZierhoffer can you help here in someway?

cc: @msaligane

**Comment by mithro** [comment]
@proppy

**Comment by proppy** [comment]
@saicharan0112 the build need to be fixed first https://github.com/hdl/conda-eda/actions/runs/3499093346/jobs/5860258677

**Comment by saicharan0112** [comment]
@proppy So this PR is not the complete solution for the openroad build?

**Comment by proppy** [comment]
@saicharan0112 the goal of that PR is to find out what need to be changed to fix the build ;)

**Comment by proppy** [comment]
@ajelinski the build seem to pass now: https://github.com/hdl/conda-eda/actions/runs/3540069944/jobs/5942702180 can  you review?

**Comment by proppy** [comment]
@QuantamHD does it look reasonable to you to disable mpl2 for now?

**Comment by saicharan0112** [comment]
Hi everyone, not sure what's stopping from merging the PR to publish the latest openroad package but just for info, but the package out there is almost 20 days old and projects like OpenFASoC relies on this package to get the latest openroad binary in the CI. I am sure others who you were encouraged to use the package are also have no access to the latest version of the binary.
It would be really helpful if we have access to the latest version of the binary in the package form in the near future.

Thanks

**Comment by QuantamHD** [comment]
Yeah you can disable it. Nothing will break, but it's not a desirable state to be in.

**Comment by QuantamHD** [comment]
@proppy Are the failing CI results related to the patch file?

**Comment by proppy** [comment]
@QuantamHD nop, the OpenROAD job itself is failing:
https://github.com/hdl/conda-eda/actions/runs/3540186266/jobs/5942944935

> Nothing will break, but it's not a desirable state to be in.

Is it surfaced in the openroad cli/ui yet? It doesn't seem that OpenLane is using yet per https://github.com/hdl/conda-eda/pull/259#issuecomment-1319494561.

**Comment by QuantamHD** [comment]
You can call it, but most people aren't using it. It's an automatic macro placer

**Comment by proppy** [comment]
Filed https://github.com/hdl/conda-eda/issues/261 to track re-enabling it.

**Comment by saicharan0112** [comment]
@proppy the openroad is still failing. Did you see that? https://github.com/hdl/conda-eda/actions/runs/3629708117/jobs/6122235621#step:3:1209

**Comment by proppy** [comment]
That's confusing because it passed in the presubmit:
https://github.com/hdl/conda-eda/actions/runs/3540186266/jobs/5942944935

@ajelinski @PiotrZierhoffer do you have a clue?

**Comment by ajelinski** [comment]
> Error: Failed to render jinja template in /home/runner/work/conda-eda/conda-eda/workdir/recipe/meta.yaml:
>  'GIT_DESCRIBE_TAG' is undefined

Such an error is almost always about problems during patches and then the details are reported below: https://github.com/hdl/conda-eda/actions/runs/3629708117/jobs/6122235621#step:3:1256
>   Command '['/home/runner/work/conda-eda/conda-eda/workdir/conda-env/bin/patch', '--no-backup-if-mismatch', '--batch', '-Np1', '-i', '/tmp/tmp9nw5r5pn/**disable-mpl2.patch**.native', '--binary', '--dry-run']' returned non-zero exit status 1.

So this is definitely about `disable-mpl2.patch` as MPL2 was disabled for macOS in the meantime: https://github.com/The-OpenROAD-Project/OpenROAD/commit/ac6fcd93f4fc88dd1bc11731b43621d2ad898d20

**Pull request merged**
