### PR TITLE
hls/xls: add stdlib

### LINKED ISSUE #234: xls package should ship dslx stdlib
and find a way to add `CONDA_PREFIX/path/to/xls` to the default loading path.

so that the package user can do:
```
import std
```
without having to extra dslx stdlib from xls source tree locally:
https://github.com/google/xls/tree/main/xls/dslx/stdlib

### PR DESCRIPTION
**Pull request by proppy**
Fixes #234

### CODE REVIEW

**Comment by proppy** [comment]
@hongted this adds the stdlib as you suggested using `//xls/tools:package_bazel_build`, not sure if we can work out something similar for https://github.com/google/xls/tree/main/xls/modules; do we even want them to be included by default? /cc @cdleary

**Comment by cdleary** [comment]
Yes I think it would make sense to include the modules e.g. in your share location there. Maybe we do as a follow on PR? These changes LGTM, thanks for doing it!

**Comment by proppy** [comment]
@cdleary maybe it's just a matter of adding the right target to the list of things we build, see https://github.com/hdl/conda-eda/pull/253/files#diff-8836aa948cf18df25f303d38b114bc159175d13dcb7ed87d76b35b2408148a16R19

Should we also include the examples?

**Comment by cdleary** [comment]
> Should we also include the examples?

Yeah I think if that's easy putting those alongside modules would give us a nice set of install contents.

**Comment by proppy** [comment]
>  a nice set of install contents.

To do this right, I think we'd need additional `filegroup` to capture the `.x` files and maybe a parent target that capture all the `dslx_library` in `modules`.

I can add it as a local patch if you don't think that's generally useful to the xls repo.

**Comment by proppy** [comment]
rebased and squashed.

**Comment by proppy** [comment]
Getting:
```
2022-12-07T00:42:21.5992988Z I1207 00:42:21.599141 139691924472768 package_bazel_build.py:326] Packaging target xls/modules/aes:aes_common_dslx...
2022-12-07T00:42:21.6002086Z Traceback (most recent call last):
2022-12-07T00:42:21.6003136Z   File "/home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/xls_1670366054274/work/bazel-bin/xls/tools/package_bazel_build.runfiles/com_google_xls/xls/tools/package_bazel_build.py", line 333, in <module>
2022-12-07T00:42:21.6003731Z     app.run(main)
2022-12-07T00:42:21.6004449Z   File "/home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/xls_1670366054274/work/bazel-bin/xls/tools/package_bazel_build.runfiles/com_google_absl_py/absl/app.py", line 303, in run
2022-12-07T00:42:21.6004968Z     _run_main(main, args)
2022-12-07T00:42:21.6005696Z   File "/home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/xls_1670366054274/work/bazel-bin/xls/tools/package_bazel_build.runfiles/com_google_absl_py/absl/app.py", line 251, in _run_main
2022-12-07T00:42:21.6006188Z     sys.exit(main(argv))
2022-12-07T00:42:21.6006915Z   File "/home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/xls_1670366054274/work/bazel-bin/xls/tools/package_bazel_build.runfiles/com_google_xls/xls/tools/package_bazel_build.py", line 327, in main
2022-12-07T00:42:21.6007440Z     packager.package_target(t)
2022-12-07T00:42:21.6008207Z   File "/home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/xls_1670366054274/work/bazel-bin/xls/tools/package_bazel_build.runfiles/com_google_xls/xls/tools/package_bazel_build.py", line 193, in package_target
2022-12-07T00:42:21.6008905Z     manifest.read(target_manifest)
2022-12-07T00:42:21.6009633Z   File "/home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/xls_1670366054274/work/bazel-bin/xls/tools/package_bazel_build.runfiles/com_google_xls/xls/tools/package_bazel_build.py", line 108, in read
2022-12-07T00:42:21.6010226Z     with open(manifest) as f:
2022-12-07T00:42:21.6011029Z FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.cache/bazel/_bazel_runner/3aaf07faeeaf1d85fde60a20f284b753/execroot/com_google_xls/bazel-out/k8-opt/bin/xls/modules/aes/aes_common_dslx.runfiles_manifest'
````

@hongted is `package_bazel_build` capable of packaging `xls_dslx_library` rules?

**Comment by proppy** [comment]
dropping the examples and modules for now, and filed #265 to defer it to another PR.

**Comment by proppy** [comment]
Merging since CI is passing and this has been keeping the openroad package out of date for quite a while now.

**Comment by ajelinski** [comment]
Sorry for not responding to your review request, somehow I overlooked it. It's nice to have it merged an it's great you added a test to the recipe. It will give more certainty for any further changes.

**Pull request merged**
