### PR TITLE
pnr: Add nextpnr-nexus

### PR DESCRIPTION
**Pull request by MateuszKosmala**
PR adds nextpnr-nexus to Place and Route.

### CODE REVIEW

**Review by ajelinski — APPROVED** [review]
It looks good. The recipe could be cleaned from unnecessary parts (e.g. Windows deps) but let's leave it because some day it might be needed on Windows too.

**Comment by ajelinski** [comment]
BTW. The package is going to be built with Python 3.7, I guess you don't need it to work with Python 3.8?

**Comment by MateuszKosmala** [comment]
Yeah, That version suits me.

**Comment by ajelinski** [comment]
The job failed. You might check if adding `-DCMAKE_INSTALL_PREFIX=/` helps as it's used in other `nextpnr`s: https://github.com/hdl/conda-eda/blob/master/pnr/nextpnr/ice40/build.sh#L6

**Comment by MateuszKosmala** [comment]
Thanks, I changed that.

**Comment by ajelinski** [comment]
I'll handle failing `symbiflow-vtr-gui-linux` in a separate PR.

**Pull request merged**
