### PR TITLE
misc/open_pdks: remove conda-forge deps

### PR DESCRIPTION
**Pull request by proppy**
- fetch conda-forge deps wheel from pipy
- install transitive deps from main

Related to #193

### CODE REVIEW

**Comment by ajelinski** [comment]
I couldn't successfully test the changes because the `magic` package built without `conda-forge` (#195) is currently broken.
Let's wait with this change until #195 is fixed and merged.

**Comment by ajelinski** [comment]
Please rebase and add `needs: ["magic-linux"]` to the CI job as it should be built before `open_pdks`: https://github.com/hdl/conda-eda/blob/master/.github/workflows/build-packages.yml#L768

**Comment by proppy** [comment]
> Please rebase and add needs: ["magic-linux"] to the CI job as it should be built before open_pdks: https://github.com/hdl/conda-eda/blob/master/.github/workflows/build-packages.yml#L768

Done.

**Comment by proppy** [comment]
restarted the CI build to make sure it picks up the latest magic version.

**Review by ajelinski — APPROVED** [review]

**Pull request merged**
